import './globals.css'
import type { Metadata } from 'next'
import { type ReactNode } from 'react'

import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en" data-theme="synthwave">
      <body className="container mx-auto">
        <Providers>{props.children}</Providers>
      </body>
    </html>
  )
}
